# 1. Array Creation Functions

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [7]:
b = np.arange(0, 10, 2)   
print("Array b:", b)

Array b: [0 2 4 6 8]


In [9]:
c = np.linspace(0, 1, 5)   
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [11]:
d = np.zeros((2, 3))   
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
e = np.ones((3, 2))   
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
f = np.eye(4)  
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [18]:
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))   
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [20]:
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)   
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [22]:
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [24]:
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [29]:
g = np.array([5, 1, 3, 4])
added = np.add(g, 2)   
print("Added 2 to g:", added)

Added 2 to g: [7 3 5 6]


In [31]:
squared = np.power(g, 2)   
print("Squared g:", squared)

Squared g: [25  1  9 16]


In [33]:
sqrt_val = np.sqrt(g)   
print("Square root of g:", sqrt_val)

Square root of g: [2.23606798 1.         1.73205081 2.        ]


In [35]:
print(a1)
print(g)

[1 2 3]
[5 1 3 4]


In [37]:
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)   
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [39]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [41]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)   
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# 4. Statistical Functions

In [44]:
s = np.array([5, 6, 7, 8])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 6.5


In [46]:
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [48]:
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 5


In [50]:
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 8


# 5. Linear Algebra Functions

In [53]:
matrix = np.array([[1, 2], [3, 4]])

In [55]:
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [57]:
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Functions

In [61]:
random_vals = np.random.rand(3)   
print("Random values:", random_vals)

Random values: [0.57594211 0.21128034 0.81957335]


In [63]:
np.random.seed(0)


random_vals = np.random.rand(3)  
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [65]:
rand_ints = np.random.randint(0, 10, size=5)  
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [67]:
np.random.seed(0)


rand_ints = np.random.randint(0, 10, size=5) 
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [70]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)   
print("All elements True:", all_true)

All elements True: False


In [72]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)   
print("All elements True:", all_true)

All elements True: False


In [74]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)   
print("All elements True:", all_true)

All elements True: False


In [76]:
any_true = np.any(logical_test)   
print("Any elements True:", any_true)

Any elements True: False


# 8. Set Operations

In [79]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [81]:
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [84]:
a = np.array([1, 2, 3])
shape = a.shape   
size = a.size    
dimensions = a.ndim  
dtype = a.dtype   

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10

In [87]:
a = np.array([1, 2, 3])
copied_array = np.copy(a)   
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [89]:
array_size_in_bytes = a.nbytes   
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [91]:
shared = np.shares_memory(a, copied_array)   
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
